### ISSUE TITLE
[Slow Your Roll] Flint Tools should be faster than stone tools. Since they're sharper and way more durable irl.

### ISSUE THREAD

**Issue by makumaku1974** [DentedLeft/Dented-Modding#11]
Just a small enhancement with flint.

**Comment by DentedLeft** [comment]
Thanks for your suggestion!  However, since Flint and Copper tools effectively replace Wooden and Stone tools respectively, the functionality should match.  I appreciate that Flint is stronger IRL, but for gameplay and balance reasons I think we're going to leave this one alone.
