### ISSUE TITLE
[Slow Your Roll] Rotten Flesh Bugged with Pale Mod 1.21

### ISSUE THREAD

**Issue by makumaku1974** [DentedLeft/Dented-Modding#13]
Pale mod essentially gives an effect to the player the Pale Effect. Which damages the player when eating rotten flesh below sunlight.
The issue is that hunger somehow replaces that mod so I think it has been rewritten.

**Comment by DentedLeft** [comment]
My mod and the Pale mod are probably both using a mixin to modify the behavior of Rotten Flesh.  I can see if I can make the two mods compatible, but this will take time.

**Comment by DentedLeft** [comment]
Compatible as of version 1.1.0.
