### ISSUE TITLE
[Slow Your Roll] New tools cannot be repaired at an anvil

### ISSUE THREAD

**Issue by BlueStaggo** [DentedLeft/Dented-Modding#15]
Copper and flint tools cannot be repaired in the anvil with their respective materials. I'm not sure if this is intentional, but it could be a bit of a let-down for anyone who's using mods to rework durability and repair.

**Comment by DentedLeft** [comment]
Thanks for raising this issue!  That behavior is definitely NOT intentional, I want flint and copper tools to be repairable.  I will fix this for the next release.

**Comment by DentedLeft** [comment]
Fixed as of version 1.0.5, closing this issue.
