### ISSUE TITLE
[Slow Your Roll] Excavated Variants' copper ores can't be mined with a flint pickaxe

### ISSUE THREAD

**Issue by BIG-Viljo** [DentedLeft/Dented-Modding#16]
This only applies to copper ores. Other ores from Excavated Variants work as intended and can be mined with appropriate pickaxe. An easy fix would be to enable flint pickaxe to mine anything with the \#minecraft:copper_ores tag.

**Comment by DentedLeft** [comment]
Thanks for raising this issue.  Using tags will increase general compatibility.  I will update this for the next release.

**Comment by DentedLeft** [comment]
Compatible as of version 1.1.0
