### ISSUE TITLE
[Slow Your Roll] Dynamic Config Customization 

### ISSUE THREAD

**Issue by makumaku1974** [DentedLeft/Dented-Modding#17]
Creating a custom config that the users can implement it themselves. Basically, adding modded items without you having to do it yourself.

**Comment by DentedLeft** [comment]
Thanks for the suggestion!  I have no idea how to implement such a feature, but maybe in the future.

**Comment by makumaku1974** [comment]
> Thanks for the suggestion! I have no idea how to implement such a feature, but maybe in the future.

This might too ambitious of a request so ill be closing it now.
