### ISSUE TITLE
[Slow Your Roll] Make food stacking changes toggleable

### ISSUE THREAD

**Issue by kckarnige** [DentedLeft/Dented-Modding#2]
A toggle or gamerule to disable/enable the food stack limit

**Comment by kckarnige** [comment]
Even if it's just a config file, I would rather have something as game-changing as that to be opt-out

**Comment by DentedLeft** [comment]
Thanks for your suggestion!
I agree. I will implement this for the next release.

**Comment by kckarnige** [comment]
Thank _you_ for making the mod of my dreams! (Seriously, I've been dreaming for a mod exactly like this one 😭)

**Comment by DentedLeft** [comment]
That means a lot! 😁

**Comment by DentedLeft** [comment]
Made toggleable as of version 1.0.3.

**Comment by kckarnige** [comment]
Hell yeah!
