### ISSUE TITLE
[Best Bundles] When putting a full bundle into new bundle, instead of refusing to do it, it just deletes the bundle

### ISSUE THREAD

**Issue by Thilpan** [DentedLeft/Dented-Modding#21]
help

**Comment by DentedLeft** [comment]
Thank you for raising this issue!  I will work on a fix for this.

**Comment by DentedLeft** [comment]
@Thilpan Out of curiosity, are you using Best Bundles or Vanilla Sprinkles?

**Comment by DentedLeft** [comment]
Fixed in version 1.0.2.

**Comment by Thilpan** [comment]
Sorry I did not see your second email, I’m using best bundles, btw is it
fixed now? Thanks

**Comment by DentedLeft** [comment]
@Thilpan Yes, the issue is fixed as of version 1.0.2
