### ISSUE TITLE
[Slow Your Roll] Compatibility with Biomes O' Plenty?

### ISSUE THREAD

**Issue by kckarnige** [DentedLeft/Dented-Modding#22]
- Add bark variants for the mod's wood types

I would do it myself, but without this mod being open source, _(and cuz I'm generally not the best with modding lmao)_ I can't really do much :p

**Comment by DentedLeft** [comment]
Thank you for the suggestion!  I'm generally not the best with modding either! :D

I'll look into compatibility, but I can't promise that it'll come anytime soon.

**Comment by kckarnige** [comment]
Alright! It's good to hear I'm not too far off the skill of a mod as great as this one, take your time on the compatibility btw *especially since there's quite a few wood types last I checked*

**Comment by DentedLeft** [comment]
Thank you for the kind and inspiring words!  Good luck to you on your journey as well!
