### ISSUE TITLE
[Netherite Mace] Is this mod is compatible with netherite upgrade template remover mod?

### ISSUE THREAD

**Issue by SUTLKRUMPLI2000** [DentedLeft/Dented-Modding#23]
I want use a netherite template remover mod, but i want a netherite mace too. So can you please make another mod, which doesn't need upgrade template to upgrade the mace. Pls make it.

**Comment by DentedLeft** [comment]
Thank you for your suggestion!

[Here](https://drive.google.com/file/d/1tgA1cAnUEHaT_-n3jlnGkBOsoOujfMkG/view?usp=drive_link) is a link to a special version just for you that uses the flow armor trim template instead.

Just this once ;)

**Comment by DentedLeft** [comment]
Closing this issue.  May reopen if request shows up again.
