### ISSUE TITLE
[Slow Your Roll] Flint Pickaxe cannot mine Copper Ore (1.21)

### ISSUE THREAD

**Issue by kckarnige** [DentedLeft/Dented-Modding#3]
I made sure to make a seperate game instance to check it out

![image](https://github.com/DentedLeft/Dented-Modding/assets/32397453/7f80cdfc-8b0f-493e-a265-c4d94c921b11)

[video](https://kckarnige.is-broke.online/dl/2024-06-24%2013-26-10_2.mp4)

**Comment by DentedLeft** [comment]
Thank you for submitting this! 
This bug is a total progression breaker. Fixed in version 1.0.2.
