### ISSUE TITLE
[Personal Disc Player] Crashing/Preventing world-load due to "test.json"

### ISSUE THREAD

**Issue by Ynaught** [DentedLeft/Dented-Modding#6]
[Version: personalplayer-1.21-1.1.3]
I'm currently reverse engineering the mod to understand the core of the issue but for now, the log reads as follows:

> > Errors in registry minecraft:jukebox_song:
> >> Errors in element personalplayer:test:
> java.lang.IllegalStateException: Failed to parse personalplayer:jukebox_song/test.json from pack personalplayer
> 	at net.minecraft.class_7655.method_45122(class_7655.java:251)
> 	at net.minecraft.class_7655$class_9158.method_56520(class_7655.java:96)
> 	at net.minecraft.class_7655.method_56514(class_7655.java:151)
> 	at net.minecraft.class_7655.method_45120(class_7655.java:164)
> 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> 	at net.minecraft.class_7655.method_45121(class_7655.java:164)
> 	at net.minecraft.class_7655.mixinextras$bridge$method_45121$33(class_7655.java)
> 	at net.minecraft.class_7655.wrapOperation$ckl000$fabric-registry-sync-v0$wrapIsServerCall(class_7655.java:556)
> 	at net.minecraft.class_7655.mixinextras$bridge$wrapOperation$ckl000$fabric-registry-sync-v0$wrapIsServerCall$36(class_7655.java)
> 	at net.minecraft.class_7655.wrapOperation$cmm000$fabric-resource-conditions-api-v1$captureRegistries(class_7655.java:1057)
> 	at net.minecraft.class_7655.method_56515(class_7655.java:151)
> 	at net.minecraft.class_7237.method_45142(class_7237.java:62)
> 	at net.minecraft.class_7237.method_45143(class_7237.java:66)
> 	at net.minecraft.class_7237.method_42098(class_7237.java:32)
> 	at net.minecraft.class_525.method_31130(class_525.java:310)
> 	at net.minecraft.class_526.method_19944(class_526.java:54)
> 	at net.minecraft.class_4185.method_25306(class_4185.java:96)
> 	at net.minecraft.class_4264.method_25348(class_4264.java:48)
> 	at net.minecraft.class_339.method_25402(class_339.java:141)
> 	at net.minecraft.class_4069.method_25402(class_4069.java:38)
> 	at net.minecraft.class_312.method_1611(class_312.java:107)
> 	at net.minecraft.class_437.method_25412(class_437.java:431)
> 	at net.minecraft.class_312.method_1601(class_312.java:107)
> 	at net.minecraft.class_312.method_22686(class_312.java:196)
> 	at net.minecraft.class_1255.execute(class_1255.java:108)
> 	at net.minecraft.class_312.method_22684(class_312.java:196)
> 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
> 	at org.lwjgl.system.JNI.invokeV(Native Method)
> 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
> 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184)
> 	at net.minecraft.class_310.method_1523(class_310.java:1310)
> 	at net.minecraft.class_310.method_1514(class_310.java:882)
> 	at net.minecraft.client.main.Main.main(Main.java:256)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: java.lang.IllegalStateException: Failed to get element ResourceKey[minecraft:sound_event / personalplayer:music_disc.test]
> 	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
> 	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
> 	at net.minecraft.class_7655.method_56915(class_7655.java:231)
> 	at net.minecraft.class_7655.method_45122(class_7655.java:249)
> 	... 35 more

**Comment by Ynaught** [comment]
If I had to guess, when this mod was uploaded. Some files were missing when published. "jukebox_song.personalplayer.test". I don't see "personalplayer" inside the folder "jukebox_song".

Also:
"personalplayer:music_disc.test"
I don't really understand thus stuff but I'm not sure what the " : " is supposed to be. And I can't seem to find a "music_disc" folder anywhere either. Perhaps you were doing some "dev testing" and then removed some of the test files but forgot to remove "all" of them and those code-remnants are breaking the mod maybe?

**Comment by Ynaught** [comment]
I just tested it with version 1.1.2 and it works fine. So I'm gonna be going through both files to see what's changed.

**Comment by DentedLeft** [comment]
You're on the right track.  For version 1.1.3 I had put in a test disc, and I must not have removed all the references to it. Embarrassing. I will put out a fix soon.

**Comment by DentedLeft** [comment]
Fixed in version 1.21-1.1.4. Thanks for your feedback!

**Comment by Ynaught** [comment]
Just following up to reconfirm. Yep. Alls good. GGs with the fix.

Now I just wish I could stuff this thing in a bundle with all the other music discs without limiting a stack size of 1. 😂
