### ISSUE TITLE
Slow Your Roll Deleted on Modrinth??

### ISSUE THREAD

**Issue by makumaku1974** [DentedLeft/Dented-Modding#7]
Recently searching this mod and it's 404

**Comment by DentedLeft** [comment]
It was temporarily taken down due to reused textures from another mod without permission. I have removed those textures and am currently waiting for it to be approved again.

**Comment by makumaku1974** [comment]
i could help. recently i have created a resourcepack for Balkon's Weapon Mod and soon to be released.

**Comment by DentedLeft** [comment]
Update: I will not be resubmitting Slow Your Roll due to needing new textures throughout the mod. 
@makumaku1974 Thank you for the offer but we are not taking texture submissions at this time. I will update this issue

**Comment by makumaku1974** [comment]
no rush

**Comment by kckarnige** [comment]
> Update: I will not be resubmitting Slow Your Roll due to needing new textures throughout the mod. @makumaku1974 Thank you for the offer but we are not taking texture submissions at this time. I will update this issue when the mod is ready to be resubmitted.

I had a heart attack when I deleted it and found the page to be gone; one of the core mods for the modpack I'm working on is this mod :sob:

**Comment by makumaku1974** [comment]
> > Update: I will not be resubmitting Slow Your Roll due to needing new textures throughout the mod. @makumaku1974 Thank you for the offer but we are not taking texture submissions at this time. I will update this issue when the mod is ready to be resubmitted.
> 
> I had a heart attack when I deleted it and found the page to be gone; one of the core mods for the modpack I'm working on is this mod 😭

Here. It includes the Bronze Compatibility. 
[mods.zip](https://github.com/user-attachments/files/16116781/mods.zip)

**Comment by kckarnige** [comment]
> > > Update: I will not be resubmitting Slow Your Roll due to needing new textures throughout the mod. @makumaku1974 Thank you for the offer but we are not taking texture submissions at this time. I will update this issue when the mod is ready to be resubmitted.
> > 
> > 
> > I had a heart attack when I deleted it and found the page to be gone; one of the core mods for the modpack I'm working on is this mod 😭
> 
> Here. It includes the Bronze Compatibility. [mods.zip](https://github.com/user-attachments/files/16116781/mods.zip)

Thank yoooou

**Comment by makumaku1974** [comment]
> > > > Update: I will not be resubmitting Slow Your Roll due to needing new textures throughout the mod. @makumaku1974 Thank you for the offer but we are not taking texture submissions at this time. I will update this issue when the mod is ready to be resubmitted.
> > > 
> > > 
> > > I had a heart attack when I deleted it and found the page to be gone; one of the core mods for the modpack I'm working on is this mod 😭
> > 
> > 
> > Here. It includes the Bronze Compatibility. [mods.zip](https://github.com/user-attachments/files/16116781/mods.zip)
> 
> Thank yoooou, btw, Bronze compatibility is still available on Modrinth, Ima update it when Slow Your Roll gets rereleased

No worries. Have a great day!

**Comment by DentedLeft** [comment]
Textures have been updated and the mod has now been submitted for review. Closing this issue.

**Comment by makumaku1974** [comment]
Can you also please nerf copper tools. Instead of ingot should be plates instead for steady roll.

**Comment by kckarnige** [comment]
> Textures have been updated and the mod has now been submitted for review. Closing this issue.

LET'S GOOOOOOO
