### ISSUE TITLE
[Personal Disc Player] Can you add in modded disc functionality?

### ISSUE THREAD

**Issue by Yo-Snowpro** [DentedLeft/Dented-Modding#9]
I have the "Discs Where Discs Shouldn't Be" Mod for my survival world and could you add functionality with that mod?
Or all disc mods if possible.

**Comment by DentedLeft** [comment]
Thanks for the suggestion! Unfortunately, I haven't figured out how to provide support for all disc mods. I have created a compatibility mod to help alleviate this. It will be available on Modrinth pending approval.

In the meantime, you can extract this to your mods folder: 
[personalplayercompat-1.21-1.0.0.zip](https://github.com/user-attachments/files/16117600/personalplayercompat-1.21-1.0.0.zip)

**Comment by DentedLeft** [comment]
https://modrinth.com/mod/personal-disc-player-compatibility will be available pending approval.

**Comment by Yo-Snowpro** [comment]
Thx for the help litterally every single creator of a mod helped except quicksort and said litterally to just do it yourself lol

**Comment by Yo-Snowpro** [comment]
I think that it makes the tracks armor trim not work somehow... What a random item
